export default {
  "HTML": "What is HTML?",
  "Useful-Docs": "Useful Docs",
  "Additional-Setup": "Additional Setup",
  "A-Simple-HTML-Program": "A Simple HTML Program",
  "Rules-For-Writing-HTML": "Rules For Writing HTML",
  "Meta-Tags": "Meta Tags",
  "Comments": "Adding Comments In HTML",
  "HTML-Tags": "HTML Tags",
  "HTML-Semantic-Elements": "HTML Semantic Elements",
  "Types-Of-Elements": "Types Of HTML Elements",
  "HTML-Attributes": "HTML Attributes",
  "Working-With-Images": "Working With Images",
  "Working-With-Forms": "Working With Forms",
  "Working-With-Tables": "Working With Tables",
  "SEO": "Search Engine Optimization",
  "HTML-Entities": "HTML Entities",
  "HTML-Events": "HTML Events",
  "What-Next": "What Next?"
}