export default {
  "CSS": "What Is CSS?",
  "Why-CSS": "Why Use CSS?",
  "CSS-Syntax": "CSS Syntax",
  "CSS-Comments": "Comments In CSS",
  "CSS-Selectors": "CSS Selectors",
  "Cascading": "The Cascading Nature Of CSS",
  "CSS-Box-Model": "The CSS Box Model",
  "CSS-Properties": "CSS Properties",
  "CSS-Vendor-Prefixes": "CSS Vendor Prefixes",
  "CSS-Rules": "CSS At-Rules",
  "Media-Queries": "CSS Media Queries And Responsiveness",
  "Deeply-Nested-Elements": "Deeply Nested Elements",
  "CSS-Functions": "CSS Functions", 
  "CSS-Variables": "CSS Variables",
  "CSS-Units": "CSS Units",
  "CSS-Pseudo-Classes": "CSS Pseudo Classes",
  "CSS-Pseudo-Elements": "CSS Pseudo Elements",
  "CSS-Colors": "Colors",
  "CSS-Color-Gradients": "Color Gradients",
  "CSS-Flexbox": "CSS Flexbox Deep Dive",
  "CSS-Grid": "CSS Grid Deep Dive",
  "CSS-Positioning": "CSS Positioning",
  "Working-With-Fonts": "Working With Fonts",
  "CSS-Global-Styles": "CSS Global Styles",
  "CSS-Animations": "Adding Animations To Webpages",
  "CSS-Entities": "CSS Entities",
  "CSS-Preprocessors": "CSS Preprocessors",
  "CSS-Cross-Browser-Compatibility": "Cross Browser Compatibility"
}
