export default {
  "Intro-To-Javascript": "Introduction to JavaScript",
  "Javascript-Interpreter": "How JavaScript is Interpreted",
  "Comments": "Comments in JavaScript",
  "Variables": "Variables",
  "Arithmetic-Operators": "Arithmetic Operators",
  "Logical-Operators": "Logical Operators",
  "Comparison-Operators": "Comparison Operators",
  "Control-Flow": "Control Flow and Conditional Statements",
  "Loops": "Loops",
  "Data-Types": "Data Types",
  "The-Typeof-Operator": "The typeof Operator",
  "Functions": "Functions",
  "Arrow-Functions": "Arrow Functions",
  "Async-Await": "Async / Await",
  "Promises": "Promises",
  "Callbacks": "Callbacks",
  "Closures": "Closures",
  "Arrays": "Arrays",
  "Sorting-Arrays": "JS Sorting Arrays",
  "Objects": "Objects",
  "Destructuring": "Array and Object Destructuring",
  "Strings": "Strings",
  "Data-Structures": "Data Structures",
  "Classes": "Classes",
  "Dates": "Dates",
  "BigInt": "BigInt",
  "Error-Handling-And-Debugging": "Error Handling and Debugging",
  "Hoisting": "Hoisting",
  "Debouncing": "Debouncing",
  "Throttling": "Throttling",
  "Javascript-Errors": "JavaScript Errors",
  "Reserved-Words": "JavaScript Reserved Words",
  "Manipulating-The-DOM": "Manipulating the DOM",
  "javascript-apis": "JavaScript Built-in APIs"
}
